# List available recipes
default:
    @just --list

# Run all workspace tests. Exclude the vendored UltraHonk verifier crate: its
# upstream suite (contracts/vendor/ultrahonk-soroban-verifier/tests/
# verifier_test.rs) reads fixture files generated by build_circuits.sh (needs
# the nargo+bb toolchain) from circuits/{simple_circuit,fib_chain}/target/,
# which we don't vendor -> "No such file or directory" on a clean checkout.
#
# This is NOT a coverage gap (see docs/SECURITY_INVARIANTS.md "Vendored
# verifier coverage"): the vendored verifier's own known-answer test is the
# `simple_circuit` proof, and nido runs those EXACT byte-identical fixtures
# through the same `UltraHonkVerifier::new(vk).verify(..)` code path at the
# contract boundary in contracts/zk-verifier/tests/verifier_smoke.rs
# (`verify_simple_circuit_proof_succeeds` + the adversarial
# `verify_with_tampered_public_inputs_fails`). On top of that, the 14
# real-`bb prove` zk_recovery_* integration tests exercise the verifier against
# the production circuit. Vendoring the upstream `fib_chain` blobs would add a
# toolchain dependency for ~zero marginal coverage of the same code, and
# editing the vendored crate to be self-contained would trip the vendor-drift
# guard (scripts/check-vendor-drift.sh). Hence: documented indirect coverage.
test:
    cargo test --workspace --exclude ultrahonk_soroban_verifier

# Build all crates (native)
build:
    cargo build --workspace

# Compile the zk_recovery Noir circuit and generate its VK/proof/public-inputs
# artifacts + manifest under circuits/zk_recovery/{target,public/circuits}.
# See circuits/zk_recovery/scripts/gen_artifacts.sh for details (falls back
# to docker for the bb steps if the local bb can't run -- e.g. glibc < 2.38).
build-circuits:
    bash circuits/zk_recovery/scripts/gen_artifacts.sh

# Rerun the zk_recovery circuit build and re-stage its vk/proof/public_inputs
# artifacts as test fixtures under crates/integration-tests/fixtures/zk/ (used
# by crates/zk-bench's real-metering budget gate and any other zk-verifier
# integration tests). Records the staged fixtures' sha256 into
# crates/integration-tests/fixtures/zk/manifest.json, alongside a pointer at
# the circuit build's own manifest (circuits/zk_recovery/public/circuits/manifest.json)
# for cross-checking provenance.
gen-zk-fixtures:
    #!/usr/bin/env bash
    set -euo pipefail
    just build-circuits
    mkdir -p crates/integration-tests/fixtures/zk
    cp circuits/zk_recovery/target/vk crates/integration-tests/fixtures/zk/vk
    cp circuits/zk_recovery/target/proof crates/integration-tests/fixtures/zk/proof
    cp circuits/zk_recovery/target/public_inputs crates/integration-tests/fixtures/zk/public_inputs
    vk_sha=$(sha256sum crates/integration-tests/fixtures/zk/vk | cut -d' ' -f1)
    proof_sha=$(sha256sum crates/integration-tests/fixtures/zk/proof | cut -d' ' -f1)
    pub_sha=$(sha256sum crates/integration-tests/fixtures/zk/public_inputs | cut -d' ' -f1)
    built_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    printf '{\n  "vkSha256": "%s",\n  "proofSha256": "%s",\n  "publicInputsSha256": "%s",\n  "sourceCircuitManifest": "circuits/zk_recovery/public/circuits/manifest.json",\n  "builtAt": "%s"\n}\n' \
        "$vk_sha" "$proof_sha" "$pub_sha" "$built_at" > crates/integration-tests/fixtures/zk/manifest.json
    echo "[ok] Staged zk fixtures + wrote manifest:"
    cat crates/integration-tests/fixtures/zk/manifest.json

# M1 Task 1: generate the pinned "lifecycle" fixture -- a REAL bb proof for
# the fixed witness in crates/integration-tests/src/zk_fixture.rs
# (account=[0x11;32], controller=[0x22;32], the Test SDF Network passphrase,
# nonce=1, timelock_secs=1_209_600 secs, a deterministic P-256 pubkey,
# single-leaf depth-24 tree). Reuses the same M0 circuit/VK, only the
# witness differs. Writes circuits/zk_recovery/fixtures/lifecycle/
# {prover_inputs.json,proof,public_inputs}. See
# circuits/zk_recovery/scripts/gen_lifecycle_fixture.sh for the full flow.
gen-zk-lifecycle-fixture:
    bash circuits/zk_recovery/scripts/gen_lifecycle_fixture.sh

# Task 4 GO/NO-GO gate: real-metering verify_proof CPU cost (<=250M gate, real 400M tx cap), measured
# against the real depth-24 circuit's proof/vk/public_inputs fixtures via a
# registered (not native) Wasm verifier contract. See
# crates/zk-bench/tests/budget.rs for the full metering methodology.
bench-zk:
    cargo test -p nido-zk-bench --test budget -- --nocapture

# Task 8 GO/NO-GO gate (FINAL M1 task): real-metering cost of the WHOLE
# `initiate_recovery` transaction (<=350M gate, real 400M
# tx_max_instructions cap) -- not just verify_proof (that's `bench-zk`
# above). Registers the REAL compiled nido_zk_recovery.wasm + M0's
# nido_zk_verifier.wasm at the pinned M1 lifecycle-fixture addresses and
# measures a single real initiate_recovery call against the real fixture
# proof. Builds the recovery contract wasm first (needed by the test's
# `include_bytes!`, which is NOT built automatically by `cargo test`). See
# crates/integration-tests/tests/it/initiate_cost.rs for the full
# methodology, including why this lives here rather than in
# crates/zk-bench.
bench-zk-initiate:
    SOROBAN_SDK_BUILD_SYSTEM_SUPPORTS_SPEC_SHAKING_V2=1 \
        cargo build -p nido-zk-recovery --target wasm32v1-none --profile contract
    cargo test -p nido-integration-tests --test it initiate_cost -- --nocapture

# Task 8 GO/NO-GO gate (FINAL M2 task) Part A: real-metering cost of the
# in-account guard's cross-call (M2 Task 4's `guard_no_pending` ->
# `has_pending`), gated at <=10M CPU (the SDF policy-cross-call target,
# distinct from `bench-zk-initiate`'s whole-transaction 350M gate). Measures
# a single `remove_signer` call: (1) against a REAL, Wasm-registered
# `nido-zk-recovery` controller with a genuine live pending (the guard
# fires, cross-calls `has_pending`, panics `RecoveryPendingBlocked`), and
# (2) as a baseline against an account with no recovery controller
# configured at all (the guard is a no-op, no cross-call). Requires all
# contract wasms (needs the recovery + verifier + smart-account wasms'
# `include_bytes!`, which is NOT built automatically by `cargo test`). See
# crates/integration-tests/tests/it/guard_cost.rs for the full methodology.
bench-zk-guard:
    just build-contracts
    cargo test -p nido-integration-tests --test it guard_cost -- --nocapture

# Build and optimize Soroban contracts.
# `stellar-scaffold build` topologically sorts the contract crates (via the
# `[package.metadata.stellar] contract = true` edges) so dependencies build
# first — notably smart-account before the factory, whose build.rs embeds the
# smart-account wasm.
#
# SOROBAN_SDK_BUILD_SYSTEM_SUPPORTS_SPEC_SHAKING_V2: scaffold invokes raw
# `cargo rustc` rather than `stellar contract build`, so it does not set the
# signal soroban-sdk 26's build script expects; we set it here (we build with a
# new enough stellar-cli) so the build does not abort on spec-shaking.
#
# Scaffold does NOT run wasm-opt, so we optimize in-place afterwards (the old
# `stellar contract build --optimize` did this); deployed wasm must stay
# optimized.
#
# Embed-freshness fix (M2 Task 8): `contracts/factory/build.rs` embeds
# smart-account's wasm bytes into the factory binary at COMPILE time, which
# happens during the `stellar-scaffold build` pass below -- i.e. BEFORE any
# optimize step runs. Optimizing everything only at the very end (as this
# recipe used to) leaves factory permanently embedding the PRE-optimize
# smart-account bytes, while every other consumer (this repo's
# `nido_integration_tests::SMART_ACCOUNT_WASM`, `stellar contract deploy` of
# the standalone wasm, ...) reads the FINAL, POST-optimize file -- a real,
# silent wasm-hash mismatch (`Wasm does not exist` when a test/deploy uploads
# the post-optimize bytes but factory's `deploy_v2` looks up the hash of its
# own stale pre-optimize embed; caught by
# `zk_recovery_e2e::dummy_and_real_enrollment_are_indistinguishable_on_chain`,
# which does exactly that). Fix: optimize smart-account FIRST, then force a
# factory-only rebuild (the same `cargo rustc` invocation `stellar-scaffold`
# itself uses for it) so its build.rs re-embeds the NOW-optimized bytes --
# its `cargo:rerun-if-changed` on the wasm path makes this a normal,
# correct incremental rebuild, not a full recompile. Everything else
# (including factory's own wasm) is optimized last, as before.
build-contracts:
    SOROBAN_SDK_BUILD_SYSTEM_SUPPORTS_SPEC_SHAKING_V2=1 stellar-scaffold build --profile contract
    stellar contract optimize \
        --wasm target/wasm32v1-none/contract/nido_smart_account.wasm \
        --wasm-out target/wasm32v1-none/contract/nido_smart_account.wasm
    CARGO_BUILD_RUSTFLAGS="--remap-path-prefix=$HOME/.cargo/registry/src=" \
        SOROBAN_SDK_BUILD_SYSTEM_SUPPORTS_SPEC_SHAKING_V2=1 \
        cargo rustc --manifest-path=contracts/factory/Cargo.toml \
            --crate-type=cdylib --target=wasm32v1-none --profile=contract
    @for wasm in target/wasm32v1-none/contract/*.wasm; do \
        case "$wasm" in *.optimized.wasm|*nido_smart_account.wasm) continue;; esac; \
        echo "→ optimize $wasm"; \
        stellar contract optimize --wasm "$wasm" --wasm-out "$wasm"; \
    done

build-ts:
    npx tsc -p ./packages/passkey-sdk/tsconfig.json

# Packages to run `cargo fmt` over -- every workspace member EXCEPT the
# vendored `ultrahonk_soroban_verifier` crate (contracts/vendor/...). That
# crate is a verbatim, checksum-guarded copy of unaudited third-party code
# (see check-vendor-drift below): reformatting its src/ tree would edit
# "vendored" bytes and permanently trip `just check-vendor-drift` on a clean
# checkout. `cargo fmt --all` has no `--exclude`/`ignore`-list support on
# stable (rustfmt's `ignore` config key is nightly-only), so the only stable
# way to exclude one workspace member is to name every OTHER member
# explicitly here instead of passing `--all`.
# NOTE: keep this list in sync with `[workspace.members]` in the root
# Cargo.toml whenever a crate is added/removed -- a crate missing from this
# list silently stops being fmt-checked.
fmt-pkgs := "-p nido-integration-tests -p nido-zk-bench -p nido-smart-account -p nido-zk-recovery -p nido-factory -p nido-multisig-policy -p nido-name-registry -p nido-preauth-sweep-policy -p nido-spending-limit-policy -p nido-status-message -p nido-webauthn-verifier -p nido-zk-verifier"

# Check formatting and clippy
check:
    cargo fmt {{fmt-pkgs}} -- --check
    cargo clippy --all --tests -- -Dclippy::pedantic

# Verify the vendored (unaudited, third-party) UltraHonk Soroban verifier
# crate under contracts/vendor/ultrahonk-soroban-verifier/src/ hasn't been
# hand-edited, by comparing its sha256 manifest against the committed
# CHECKSUMS.sha256. See scripts/check-vendor-drift.sh for details and how
# to regenerate the baseline after a deliberate, reviewed vendor bump.
check-vendor-drift:
    bash scripts/check-vendor-drift.sh

# Format all code (see fmt-pkgs above for why the vendored verifier crate is
# excluded).
fmt:
    cargo fmt {{fmt-pkgs}}

# Clean build artifacts
clean:
    cargo clean

check-astro:
    npx astro check --root ./packages/frontend

build-astro:
    npx astro build --root ./packages/frontend

cloudflare-deploy: build-astro
    npx wrangler pages deploy packages/frontend/dist/ --project-name mysoroban --branch main

dev: build-ts
    (cd packages/frontend; npm run dev)

# Run Tasks 4 & 4b: publish + deploy multisig-policy via stellar-registry,
# publish + upgrade factory. See scripts/deploy-policy-builder-v1.sh for what
# it does and the env-var overrides.
publish-policy-builder-v1 alias network="testnet":
    ./scripts/deploy-policy-builder-v1.sh {{alias}} {{network}}

# Deploy a Nido-owned stellar-registry instance and register factory/verifier/
# zk-recovery into it (plan A3). Fetches the reference registry wasm, redeploys
# it under our owner, records the wasm hash. Rehearse on testnet before mainnet;
# set FACTORY/VERIFIER/ZK_RECOVERY (+ OWNER/ctor args). See scripts/deploy-registry.sh.
publish-registry alias network="testnet":
    ./scripts/deploy-registry.sh {{alias}} {{network}}

# Regenerate one binding from a fresh .wasm and apply post-gen fixes.
# Usage: just bindings smart-account
# Run after `just build-contracts`. See scripts/fix-bindings.sh for what
# the post-gen pass does (stellar-sdk pin alignment + Context shim).
bindings name:
    stellar contract bindings typescript \
        --overwrite \
        --output-dir packages/contract-bindings/{{name}} \
        --wasm target/wasm32v1-none/contract/nido_{{replace(name, '-', '_')}}.wasm
    ./scripts/fix-bindings.sh

# Regenerate ALL bindings (assumes wasms in target/) and apply post-gen
# fixes once at the end.
bindings-all:
    @for name in smart-account factory multisig-policy webauthn-verifier; do \
        wasm="target/wasm32v1-none/contract/nido_$$(echo $$name | tr - _).wasm"; \
        echo "→ $$name ($$wasm)"; \
        stellar contract bindings typescript --overwrite \
            --output-dir packages/contract-bindings/$$name \
            --wasm "$$wasm"; \
    done
    ./scripts/fix-bindings.sh

# Run TestAuthenticator unit tests (vitest, node)
test-support:
    npx vitest run --config vitest.support.config.ts

# Fast UI e2e tier (shim) across all browsers; builds the frontend first
test-e2e: build-astro
    npx playwright test --grep @fast

# Chromium CDP virtual-authenticator fidelity lane; builds the frontend first
test-e2e-cdp: build-astro
    npx playwright test --project=chromium-cdp

# Sources tests/.env.testnet if present (set NIDO_TEST_BANK_SECRET there to a
# funded testnet G-account secret to skip friendbot for the name submitter);
# otherwise the app funds its own submitter via friendbot.
# Quarantined real-testnet e2e tier (create+deploy + name-claim); builds first
test-e2e-testnet: build-astro
    #!/usr/bin/env bash
    set -euo pipefail
    if [ -f tests/.env.testnet ]; then set -a; source tests/.env.testnet; set +a; fi
    npx playwright test --project=testnet-chromium --project=testnet-webkit
